server:
  port:
    8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/ai-assistant-db"
    username: postgres
    password: postgres
  application:
    name: "my-local-ai-assistant"
  ai:
    ollama:
      base-url: "http://localhost:11434"
      chat:
        model: "gemma3:4b-it-q4_K_M"

chat:
  history:
    context-limit: 2